### ISSUE TITLE
Uncaught TypeError: Cannot read property 'regl' of undefined

### ISSUE THREAD

**Issue by diego30** [ojack/atom-hydra#10]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.37.0 x64
**Electron**: 2.0.18
**OS**: Mac OS X 10.11.6
**Thrown From**: [atom-hydra](https://github.com/ojack/atom-hydra) package 0.2.10

### Stack Trace

Uncaught TypeError: Cannot read property 'regl' of undefined

```
At /Users/diego/.atom/packages/atom-hydra/lib/main.js:229

TypeError: Cannot read property 'regl' of undefined
    at Main.stop (/packages/atom-hydra/lib/main.js:229:16)
    at Object.toggle (/packages/atom-hydra/lib/atom-hydra.js:40:24)
    at HTMLElement.atomHydraToggle (/packages/atom-hydra/lib/atom-hydra.js:18:39)
    at CommandRegistry.handleCommandEvent (/Users/diego/Downloads/Atom.app/Contents/Resources/app/static/<embedded>:11:349922)
    at CommandRegistry.dispatch (/Users/diego/Downloads/Atom.app/Contents/Resources/app/static/<embedded>:11:348397)
    at AtomEnvironment.dispatchApplicationMenuCommand (/Users/diego/Downloads/Atom.app/Contents/Resources/app/static/<embedded>:1:716177)
    at EventEmitter.t (/Users/diego/Downloads/Atom.app/Contents/Resources/app/static/<embedded>:1:724100)
    at emitThree (events.js:136:13)
    at EventEmitter.emit (events.js:217:7)
```

### Commands

```
  2x -0:31.1.0 core:copy (atom-notification.fatal.icon.icon-bug.native-key-bindings.has-detail.has-close.has-stack)
```

### Non-Core Packages

```
atom-hydra 0.2.10 
tidalcycles 3.0.0 
```

**Comment by endrorytm** [comment]
i'm sorry but i'm newbie 
i can you fix the problem "Uncaught TypeError: Cannot read property 'clear' of undefined" 
need help
