### ISSUE TITLE
Uncaught TypeError: Cannot redefine property: ontrack

### ISSUE THREAD

**Issue by etarts** [ojack/atom-hydra#13]
[Enter steps to reproduce:]

1. Trying to install in Atom on Lubuntu16.04 64 bit
2. ...

**Atom**: 1.38.2 x64
**Electron**: 2.0.18
**OS**: Ubuntu 16.04.6
**Thrown From**: [atom-hydra](https://github.com/ojack/atom-hydra) package 0.2.10

### Stack Trace

Uncaught TypeError: Cannot redefine property: ontrack

```
At /home/et/.atom/packages/atom-hydra/node_modules/webrtc-adapter/dist/utils.js:80

TypeError: Cannot redefine property: ontrack
    at Function.defineProperty (<anonymous>)
    at Object.wrapPeerConnectionEvent (/packages/atom-hydra/node_modules/webrtc-adapter/dist/utils.js:80:10)
    at Object.shimOnTrack (/packages/atom-hydra/node_modules/webrtc-adapter/dist/chrome/chrome_shim.js:124:11)
    at adapterFactory (/packages/atom-hydra/node_modules/webrtc-adapter/dist/adapter_factory.js:79:18)
    at /packages/atom-hydra/node_modules/webrtc-adapter/dist/adapter_core.js:18:51)
    at /packages/atom-hydra/node_modules/webrtc-adapter/dist/adapter_core.js:21:3)
    at Module.get_Module._compile (/usr/share/atom/resources/app/static/<embedded>:11:147172)
    at Object.value [as .js] (/usr/share/atom/resources/app/static/<embedded>:11:150720)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:60:45)
    at require (/usr/share/atom/resources/app/static/<embedded>:11:146462)
    at /packages/atom-hydra/node_modules/hydra-synth/src/lib/getscreenmedia.js:1:170)
    at /packages/atom-hydra/node_modules/hydra-synth/src/lib/getscreenmedia.js:210:3)
    at Module.get_Module._compile (/usr/share/atom/resources/app/static/<embedded>:11:147172)
    at Object.value [as .js] (/usr/share/atom/resources/app/static/<embedded>:11:150720)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:60:45)
    at require (/usr/share/atom/resources/app/static/<embedded>:11:146462)
    at /packages/atom-hydra/node_modules/hydra-synth/src/lib/screenmedia.js:1:179)
    at /packages/atom-hydra/node_modules/hydra-synth/src/lib/screenmedia.js:39:3)
    at Module.get_Module._compile (/usr/share/atom/resources/app/static/<embedded>:11:147172)
    at Object.value [as .js] (/usr/share/atom/resources/app/static/<embedded>:11:150720)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:60:45)
```

### Commands

```
  3x -4:21.5.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
atom-hydra 0.2.10 
```

**Comment by ojack** [comment]
I recently started getting this error as well but I am having trouble reproducing it. I think it might be somehow interfering with other packages in atom, but I am not sure. If you get a chance could you try installing on a fresh version of atom with no other packages installed?

**Comment by XiNNiW** [comment]
I'm not sure if this is helpful but i recently re-installed the hydra-atom package which caused its version number of the atom-synth package to go from 1.0.18 to 1.0.22 and started to get the error all of a sudden. It could be a coincidence though as the stack trace is in another module.

**Comment by msarchet** [comment]
I've ran into this bug as well.

I fixed it by adding this line into the webrtc-adapter/dist/utils.js files

in hydra-atom this is at node_modules/webrtc-adapter/dist/util.js:80

```
  // add lines to prevent exception on duplicate event name wrapping
  if (Object.getOwnPropertyNames(proto).indexOf('on' + eventNameToWrap) != -1) {
    return;
  }
  
Object.defineProperty(proto, 'on' + eventNameToWrap, {
```
I don't know if the event name is coming from hydra yet? or if it is a webrtc-adapter problem, but based on this being in module load I would think it's a problem with webrtc-adapter. so I'm going to go open a bug there too.

**Comment by msarchet** [comment]
I also ran into this having lots of problems getting atom-hydra to work and I after this change I haven't had any additional issues with it.

**Comment by fippo** [comment]
speaking as one of the people who has maintained the getusermedia package (which seems to pull in adapter@2) in the past: get rid of it and use navigator.mediaDevices.getUserMedia directly.

**Comment by celebie** [comment]
having same error!

TypeError: Cannot redefine property: ontrack
    at Function.defineProperty (<anonymous>)
    at Object.wrapPeerConnectionEvent (/Users/kudret/.atom/packages/atom-hydra/node_modules/webrtc-adapter/dist/utils.js:80:10)
    at Object.shimOnTrack (/Users/kudret/.atom/packages/atom-hydra/node_modules/webrtc-adapter/dist/chrome/chrome_shim.js:124:11)
    at adapterFactory (/Users/kudret/.atom/packages/atom-hydra/node_modules/webrtc-adapter/dist/adapter_factory.js:79:18)
    at Object.<anonymous> (/Users/kudret/.atom/packages/atom-hydra/node_modules/webrtc-adapter/dist/adapter_core.js:18:51)
    at Object.<anonymous> (/Users/kudret/.atom/packages/atom-hydra/node_modules/webrtc-adapter/dist/adapter_core.js:21:3)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:147172)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:150720)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.js:60:45)
    at require (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:146462)
    at Object.<anonymous> (/Users/kudret/.atom/packages/atom-hydra/node_modules/hydra-synth/src/lib/getscreenmedia.js:1:170)
    at Object.<anonymous> (/Users/kudret/.atom/packages/atom-hydra/node_modules/hydra-synth/src/lib/getscreenmedia.js:210:3)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:147172)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:150720)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.js:60:45)
    at require (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:146462)
    at Object.<anonymous> (/Users/kudret/.atom/packages/atom-hydra/node_modules/hydra-synth/src/lib/screenmedia.js:1:179)
    at Object.<anonymous> (/Users/kudret/.atom/packages/atom-hydra/node_modules/hydra-synth/src/lib/screenmedia.js:39:3)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:147172)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:150720)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.js:60:45)
