### ISSUE TITLE
Uncaught TypeError: this.output.getCurrent is not a function

### ISSUE THREAD

**Issue by Deetoxico** [ojack/atom-hydra#18]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.40.1 x64
**Electron**: 3.1.10
**OS**: Mac OS X 10.15
**Thrown From**: [atom-hydra](https://github.com/ojack/atom-hydra) package 0.2.12

### Stack Trace

Uncaught TypeError: this.output.getCurrent is not a function

```
At /Users/benjaminverduzco/.atom/packages/atom-hydra/node_modules/hydra-synth/index.js:336

TypeError: this.output.getCurrent is not a function
    at HydraSynth.tick (/packages/atom-hydra/node_modules/hydra-synth/index.js:336:27)
    at /packages/atom-hydra/lib/main.js:216:20)
    at Engine.emit (events.js:182:13)
    at Engine.tick (/packages/atom-hydra/node_modules/raf-loop/index.js:42:10)
```

### Commands

```
     -2:14.3.0 core:move-up (input.hidden-input)
  8x -2:10.5.0 core:backspace (input.hidden-input)
     -2:05.4.0 editor:newline (input.hidden-input)
     -2:02.1.0 atom-hydra:evalBlock (input.hidden-input)
     -1:52.9.0 core:backspace (input.hidden-input)
     -1:51.3.0 atom-hydra:evalBlock (input.hidden-input)
  3x -1:44.8.0 core:move-up (input.hidden-input)
  2x -1:43.8.0 core:backspace (input.hidden-input)
     -1:43 atom-hydra:evalBlock (input.hidden-input)
 14x -0:24.7.0 core:move-down (input.hidden-input)
  2x -0:20.9.0 editor:newline (input.hidden-input)
     -0:17.8.0 atom-hydra:evalBlock (input.hidden-input)
     -0:14.4.0 core:move-left (input.hidden-input)
     -0:12.8.0 atom-hydra:evalBlock (input.hidden-input)
  2x -0:10 core:backspace (input.hidden-input)
     -0:07.9.0 atom-hydra:evalBlock (input.hidden-input)
```

### Non-Core Packages

```
atom-hydra 0.2.12 
```

**Comment by ojack** [comment]
Hi, this is most likely an error with your hydra code, rather than the package. (atom suggests reporting by default). I will close the issue, but feel free to paste your code here for troubleshooting, or ask in the hydra discord (https://discord.gg/uYfHh57s) for quicker replies :)
