### ISSUE TITLE
Uncaught TypeError: x.getTexture is not a function

### ISSUE THREAD

**Issue by betweenhangovers** [ojack/atom-hydra#22]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.44.0 x64
**Electron**: 4.2.7
**OS**: Mac OS X 10.15.3
**Thrown From**: [atom-hydra](https://github.com/ojack/atom-hydra) package 0.2.14

### Stack Trace

Uncaught TypeError: x.getTexture is not a function

```
At /Users/Bamboleobamboleo/.atom/packages/atom-hydra/node_modules/hydra-synth/src/GeneratorFactory.js:97

TypeError: x.getTexture is not a function
    at Object.typedArg.value (/packages/atom-hydra/node_modules/hydra-synth/src/GeneratorFactory.js:97:33)
    at Object.draw (/packages/atom-hydra/node_modules/regl/dist/regl.js:5557:25), <anonymous>:355:11)
    at /packages/atom-hydra/node_modules/regl/dist/regl.js:9445:21)
    at passes.forEach (/packages/atom-hydra/node_modules/hydra-synth/src/output.js:164:38)
    at Array.forEach (<anonymous>)
    at Output.tick (/packages/atom-hydra/node_modules/hydra-synth/src/output.js:164:15)
    at HydraSynth.tick (/packages/atom-hydra/node_modules/hydra-synth/index.js:316:17)
    at /packages/atom-hydra/lib/main.js:216:20)
    at Engine.emit (events.js:182:13)
    at Engine.tick (/packages/atom-hydra/node_modules/raf-loop/index.js:42:10)
```

### Commands

```
     -2:04.2.0 atom-hydra:evalBlock (input.hidden-input)
  2x -2:02.7.0 editor:newline (input.hidden-input)
     -1:42.9.0 atom-hydra:evalBlock (input.hidden-input)
     -1:41.9.0 editor:newline (input.hidden-input)
     -1:36.5.0 core:backspace (input.hidden-input)
     -1:35.7.0 atom-hydra:evalBlock (input.hidden-input)
     -1:34.9.0 core:move-right (input.hidden-input)
     -1:33.2.0 atom-hydra:evalBlock (input.hidden-input)
  2x -1:25.5.0 editor:newline (input.hidden-input)
     -1:13.5.0 core:backspace (input.hidden-input)
     -1:12.8.0 core:move-right (input.hidden-input)
     -1:01.3.0 atom-hydra:evalBlock (input.hidden-input)
  2x -0:38 editor:newline (input.hidden-input)
     -0:32.1.0 atom-hydra:evalBlock (input.hidden-input)
     -0:31.1.0 editor:newline (input.hidden-input)
  3x -0:28.8.0 atom-hydra:evalBlock (input.hidden-input)
```

### Non-Core Packages

```
atom-hydra 0.2.14 
tidalcycles 3.8.7 
```

**Comment by ojack** [comment]
Hi, this is most likely an error with your hydra code, rather than the package. (atom suggests reporting by default). I will close the issue, but feel free to paste your code here for troubleshooting, or ask in the hydra discord (https://discord.gg/uYfHh57s) for quicker replies :)
