### ISSUE TITLE
Failed to activate the atom-hydra package

### ISSUE THREAD

**Issue by santiagoitzcoatl** [ojack/atom-hydra#24]
Hi Olivia!

I was updating my Atom, but it failed to run Hydra.
I wonder if I can just manually add the glsl package

[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.40.0 x64
**Electron**: 3.1.10
**OS**: Mac OS X 10.10.5
**Thrown From**: [atom-hydra](https://github.com/ojack/atom-hydra) package 0.2.14

### Stack Trace

Failed to activate the atom-hydra package

```
At Cannot find module 'glsl-fast-gaussian-blur' from '/Users/Santiago/.atom/packages/atom-hydra/node_modules/hydra-synth/src/glsl'

Error: Cannot find module 'glsl-fast-gaussian-blur' from '/Users/Santiago/.atom/packages/atom-hydra/node_modules/hydra-synth/src/glsl'
    at Function.module.exports [as sync] (/Users/Santiago/node_modules/glsl-resolve/node_modules/resolve/lib/sync.js:32:11)
    at Depper.resolveSync [as resolve] (/Users/Santiago/node_modules/glsl-resolve/index.js:33:19)
    at /Users/Santiago/node_modules/glslify-deps/sync.js:156:27
    at Array.forEach (<anonymous>)
    at resolveImports (/Users/Santiago/node_modules/glslify-deps/sync.js:149:13)
    at Depper.add (/Users/Santiago/node_modules/glslify-deps/sync.js:128:3)
    at Object.file (/Users/Santiago/node_modules/glslify/index.js:53:23)
    at module.exports (/Users/Santiago/node_modules/glslify/index.js:18:20)
    at /packages/atom-hydra/node_modules/hydra-synth/src/glsl/renderpass-functions.js:23:11)
    at /packages/atom-hydra/node_modules/hydra-synth/src/glsl/renderpass-functions.js:27:3)
    at Module.get_Module._compile (/Users/Santiago/Desktop/Atom.app/Contents/Resources/app/static/<embedded>:11:147429)
    at Object.value [as .js] (/Users/Santiago/Desktop/Atom.app/Contents/Resources/app/static/<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (/Users/Santiago/Desktop/Atom.app/Contents/Resources/app/static/<embedded>:11:146745)
    at /packages/atom-hydra/node_modules/hydra-synth/src/generator-factory.js:4:29)
    at /packages/atom-hydra/node_modules/hydra-synth/src/generator-factory.js:95:3)
    at Module.get_Module._compile (/Users/Santiago/Desktop/Atom.app/Contents/Resources/app/static/<embedded>:11:147429)
    at Object.value [as .js] (/Users/Santiago/Desktop/Atom.app/Contents/Resources/app/static/<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (/Users/Santiago/Desktop/Atom.app/Contents/Resources/app/static/<embedded>:11:146745)
    at /packages/atom-hydra/node_modules/hydra-synth/hydra-synth.js:10:15)
    at /packages/atom-hydra/node_modules/hydra-synth/hydra-synth.js:390:3)
    at Module.get_Module._compile (/Users/Santiago/Desktop/Atom.app/Contents/Resources/app/static/<embedded>:11:147429)
    at Object.value [as .js] (/Users/Santiago/Desktop/Atom.app/Contents/Resources/app/static/<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (/Users/Santiago/Desktop/Atom.app/Contents/Resources/app/static/<embedded>:11:146745)
    at /packages/atom-hydra/node_modules/hydra-synth/index.js:1:170)
```

### Commands

```
     -0:35.1.0 atom-hydra:toggle (input.hidden-input)
     -0:18.6.0 core:copy (atom-notification.fatal.icon.icon-bug.native-key-bindings.has-detail.has-close.has-stack)
```

### Non-Core Packages

```
arduino-upload 1.7.0 
atom-beautify 0.33.4 
atom-hydra 0.2.14 
atom-processing 0.1.2 
atom-python-run 0.9.7 
atom-runner 2.7.1 
build-processing 0.1.2 
console-panel 0.3.1 
cssbeautify 1.3.0 
dash 1.7.1 
htmlhint 1.1.4 
language-arduino 0.4.3 
language-lua 0.9.11 
perfectionist 2.0.0 
processing-atom 1.1.0 
processing-autocomplete 0.2.0 
processing-language 0.2.0 
python-runner 1.2.1 
remote-atom 1.3.12 
rhino-python 0.8.4 
script 3.18.1 
styri-syntax 1.0.0 
tidal-autocode 0.6.4 
tidalcycles 3.8.7 
```

**Comment by santiagoitzcoatl** [comment]
In order to make it work, I had to comment `renderpass-functions.js` in `/Users/Santiago/.atom/packages/atom-hydra/node_modules/hydra-synth/src/glsl`

**Comment by ojack** [comment]
Hey I just pushed a new verion of hydra-synth commenting renderpass-functions. Let me know if it works!

**Comment by ojack** [comment]
hi @santiagoitzcoatl any updates?
