### ISSUE TITLE
Installation of atom-hydra@0.2.15 failed during phantomjs-prebuilt@2.1.16 

### ISSUE THREAD

**Issue by metagrowing** [ojack/atom-hydra#31]
Installation of atom-hydra@0.2.15 failed during phantomjs-prebuilt@2.1.16 

I am getting a ELIFECYCLE error while trying to install the atom-hydra package.

using 
Debian GNU/Linux 10 (buster)
Atom 1.47.0

```
4155 verbose stack Error: phantomjs-prebuilt@2.1.16 install: `node install.js`
4155 verbose stack Exit status 134
4155 verbose stack     at EventEmitter.<anonymous> (/usr/share/atom/resources/app/apm/node_modules/npm/node_modules/npm-lifecycle/index.js:304:16)
4155 verbose stack     at EventEmitter.emit (events.js:182:13)
4155 verbose stack     at ChildProcess.<anonymous> (/usr/share/atom/resources/app/apm/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
4155 verbose stack     at ChildProcess.emit (events.js:182:13)
4155 verbose stack     at maybeClose (internal/child_process.js:961:16)
4155 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:5)
4156 verbose pkgid phantomjs-prebuilt@2.1.16
4157 verbose cwd /tmp/apm-install-dir-202057-8824-1ue4356.8188
4158 verbose Linux 4.19.0-9-amd64
4159 verbose argv "/usr/share/atom/resources/app/apm/bin/node" "/usr/share/atom/resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/home/strom/.atom/.apm/.apmrc" "--userconfig" "/home/strom/.atom/.apmrc" "install" "https://www.atom.io/api/packages/atom-hydra/versions/0.2.15/tarball" "--target=5.0.13" "--disturl=https://atom.io/download/electron" "--arch=x64" "--global-style"
4160 verbose node v10.2.1
4161 verbose npm  v6.2.0
4162 error code ELIFECYCLE
4163 error errno 134
4164 error phantomjs-prebuilt@2.1.16 install: `node install.js`
```
[phantomjs-prebuilt.log](https://github.com/ojack/atom-hydra/files/4741543/phantomjs-prebuilt.log)

**Comment by metagrowing** [comment]
Looks like nodejs in the Debian 10 (Buster) repository is an old version.

This worked for me:
Deinstalling nodejs 10.21.0 from my Debian box.
Installing nodejs 12.18.0-1nodesource1 from deb.nodesource.com
See: https://nodejs.dev/  Go to „apt-get(Debian)“

Now I can use Hydra inside Atom.
