### ISSUE TITLE
Uncaught Error: (regl) bad data or missing for uniform "radius0".  invalid type, expected number ...

### ISSUE THREAD

**Issue by jebojorquez** [ojack/atom-hydra#39]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.55.0 x64
**Electron**: 6.1.12
**OS**: Microsoft Windows 10 Home
**Thrown From**: [atom-hydra](https://github.com/ojack/atom-hydra) package 0.3.2

### Stack Trace

Uncaught Error: (regl) bad data or missing for uniform "radius0".  invalid type, expected number in command C:\Users\Raveen\.atom\packages\atom-hydra\node_modules\hydra-synth\src\output.js:104:20

```
At C:\Users\Raveen\.atom\packages\atom-hydra\node_modules\regl\dist\regl.js:49

Error: (regl) bad data or missing for uniform "radius0".  invalid type, expected number in command C:\Users\Raveen\.atom\packages\atom-hydra\node_modules\hydra-synth\src\output.js:104:20
    at raise (/packages/atom-hydra/node_modules/regl/dist/regl.js:47:15)
    at Function.commandRaise (/packages/atom-hydra/node_modules/regl/dist/regl.js:402:3)
    at Output.draw (/packages/atom-hydra/node_modules/regl/dist/regl.js:5897:25), <anonymous>:345:34)
    at /packages/atom-hydra/node_modules/regl/dist/regl.js:9991:21)
    at Output.tick (/packages/atom-hydra/node_modules/hydra-synth/src/output.js:120:8)
    at HydraRenderer.tick (/packages/atom-hydra/node_modules/hydra-synth/hydra-synth.js:396:19)
    at /packages/atom-hydra/lib/main.js:226:20)
    at Engine.emit (events.js:200:13)
    at Engine.tick (/packages/atom-hydra/node_modules/raf-loop/index.js:42:10)
```

### Commands

```
     -1:40.1.0 core:move-right (input.hidden-input)
  2x -1:39.5.0 core:backspace (input.hidden-input)
     -1:33.3.0 atom-hydra:evalLine (input.hidden-input)
  4x -1:31.6.0 core:move-up (input.hidden-input)
  4x -1:30 atom-hydra:evalLine (input.hidden-input)
     -1:01.6.0 tidalcycles:eval (input.hidden-input)
     -0:54.7.0 atom-hydra:evalLine (input.hidden-input)
  3x -0:54 core:move-up (input.hidden-input)
     -0:53 atom-hydra:evalLine (input.hidden-input)
  7x -0:52.6.0 core:move-down (input.hidden-input)
     -0:51 atom-hydra:evalLine (input.hidden-input)
  5x -0:49.9.0 core:move-down (input.hidden-input)
     -0:48.4.0 core:move-up (input.hidden-input)
     -0:48 atom-hydra:evalLine (input.hidden-input)
  2x -0:39.1.0 atom-hydra:toggle (input.hidden-input)
  2x -0:33.5.0 atom-hydra:evalLine (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-html-preview 0.2.6 
atom-hydra 0.3.2 
atom-ternjs 0.20.0 
autoclose-html 0.23.0 
busy-signal 2.0.1 
emmet 2.4.3 
hyperclick 0.1.5 
intentions 1.1.5 
language-ejs 0.4.0 
linter 2.3.1 
linter-eslint 8.5.5 
linter-ui-default 1.8.1 
pigments 0.40.6 
Sublime-Style-Column-Selection 1.7.5 
tidalcycles 3.16.6 
```

**Comment by ojack** [comment]
Hi, this is usually an error with your hydra code, rather than the package. (atom suggests reporting by default) I will close the issue, but feel free to paste your code here for troubleshooting :)
