### ISSUE TITLE
Uncaught Error: (regl) bad data or missing for uniform "speed2".  invalid type, expected number i...

### ISSUE THREAD

**Issue by melodyloveless** [ojack/atom-hydra#44]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.58.0 x64
**Electron**: 9.4.4
**OS**: Mac OS X 10.14.6
**Thrown From**: [atom-hydra](https://github.com/ojack/atom-hydra) package 0.3.2

### Stack Trace

Uncaught Error: (regl) bad data or missing for uniform "speed2".  invalid type, expected number in command /Users/professorloveless/.atom/packages/atom-hydra/node_modules/hydra-synth/src/output.js:104:20

```
At /Users/professorloveless/.atom/packages/atom-hydra/node_modules/regl/dist/regl.js:49

Error: (regl) bad data or missing for uniform "speed2".  invalid type, expected number in command /Users/professorloveless/.atom/packages/atom-hydra/node_modules/hydra-synth/src/output.js:104:20
    at raise (/packages/atom-hydra/node_modules/regl/dist/regl.js:47:15)
    at Function.commandRaise (/packages/atom-hydra/node_modules/regl/dist/regl.js:402:3)
    at Output.draw (/packages/atom-hydra/node_modules/regl/dist/regl.js:5897:25), <anonymous>:351:34)
    at /packages/atom-hydra/node_modules/regl/dist/regl.js:9991:21)
    at Output.tick (/packages/atom-hydra/node_modules/hydra-synth/src/output.js:120:8)
    at HydraRenderer.tick (/packages/atom-hydra/node_modules/hydra-synth/hydra-synth.js:396:19)
    at /packages/atom-hydra/lib/main.js:226:20)
    at Engine.emit (events.js:223:5)
    at Engine.tick (/packages/atom-hydra/node_modules/raf-loop/index.js:42:10)
```

### Commands

```
     -0:39.2.0 atom-hydra:toggle (input.hidden-input)
  5x -0:37.8.0 atom-hydra:evalBlock (input.hidden-input)
  2x -0:28.7.0 core:backspace (input.hidden-input)
     -0:27.6.0 atom-hydra:evalBlock (input.hidden-input)
     -0:26.3.0 core:move-down (input.hidden-input)
     -0:25.9.0 core:move-right (input.hidden-input)
     -0:24.9.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
atom-hydra 0.3.2 
atom-live-server 2.3.0 
atom-sonic 0.3.2 
color-picker 2.3.0 
foxdot 1.3.0 
local-web-server 0.1.0 
markdown-pdf 2.3.3 
moonbeam-syntax 0.8.2 
sb-atom-sonic-pi 1.0.0-beta.3 
seti-syntax 1.2.0 
tidalcycles 3.16.14 
```

**Comment by melodyloveless** [comment]
I'm not sure if I'm doing something wrong (checking my syntax now) but thought I'd submit this since the package suggested to
