### ISSUE TITLE
Uncaught Error: (regl) bad data or missing for uniform "frequency1".  invalid type, expected numb...

### ISSUE THREAD

**Issue by KushaKenichi** [ojack/atom-hydra#7]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.33.1 x64
**Electron**: 2.0.16
**OS**: Mac OS X 10.14
**Thrown From**: [atom-hydra](https://github.com/ojack/atom-hydra) package 0.2.10

### Stack Trace

Uncaught Error: (regl) bad data or missing for uniform "frequency1".  invalid type, expected number in command /Users/user/.atom/packages/atom-hydra/node_modules/hydra-synth/src/output.js:139:20

```
At /Users/user/.atom/packages/atom-hydra/node_modules/regl/dist/regl.js:49

Error: (regl) bad data or missing for uniform "frequency1".  invalid type, expected number in command /Users/user/.atom/packages/atom-hydra/node_modules/hydra-synth/src/output.js:139:20
    at raise (/packages/atom-hydra/node_modules/regl/dist/regl.js:47:15)
    at Function.commandRaise (/packages/atom-hydra/node_modules/regl/dist/regl.js:390:3)
    at Object.draw (/packages/atom-hydra/node_modules/regl/dist/regl.js:5549:25), <anonymous>:351:34)
    at /packages/atom-hydra/node_modules/regl/dist/regl.js:9435:21)
    at passes.forEach (/packages/atom-hydra/node_modules/hydra-synth/src/output.js:158:38)
    at Array.forEach (<anonymous>)
    at Output.tick (/packages/atom-hydra/node_modules/hydra-synth/src/output.js:158:15)
    at HydraSynth.tick (/packages/atom-hydra/node_modules/hydra-synth/index.js:301:17)
    at /packages/atom-hydra/lib/main.js:216:20)
    at emitOne (events.js:116:13)
    at Engine.emit (events.js:211:7)
    at Engine.tick (/packages/atom-hydra/node_modules/raf-loop/index.js:42:10)
```

### Commands

```
     -1:36.5.0 core:backspace (input.hidden-input)
     -1:35.4.0 atom-hydra:evalBlock (input.hidden-input)
     -1:33.9.0 core:backspace (input.hidden-input)
     -1:32.8.0 atom-hydra:evalBlock (input.hidden-input)
     -1:32.3.0 core:backspace (input.hidden-input)
  2x -1:31.3.0 atom-hydra:evalBlock (input.hidden-input)
     -1:08.6.0 editor:newline-below (input.hidden-input)
     -1:07.4.0 core:backspace (input.hidden-input)
     -1:06.8.0 jumpy:toggle (input.hidden-input)
     -1:05.9.0 jumpy:clear (input.hidden-input)
     -1:05.1.0 jumpy:toggle (input.hidden-input)
     -0:50.4.0 core:move-left (input.hidden-input)
     -0:49.7.0 core:backspace (input.hidden-input)
     -0:49.2.0 jumpy:toggle (input.hidden-input)
     -0:47.5.0 jumpy:clear (input.hidden-input)
     -0:45.9.0 atom-hydra:evalBlock (input.hidden-input)
```

### Non-Core Packages

```
atom-hydra 0.2.10 
atom-pair 2.0.13 
jumpy 5.0.2 
tidal-autocode 0.6.4 
tidalcycles 0.13.0 
veda 2.10.2 
```

**Comment by ojack** [comment]
What code were you running when this error was thrown?

**Comment by ojack** [comment]
Closing this error as it is most likely related to your code.
