### ISSUE TITLE
Uncaught Error: (regl) webgl not supported, try upgrading your browser or graphics drivers http:/...

### ISSUE THREAD

**Issue by diego30** [ojack/atom-hydra#9]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.37.0 x64
**Electron**: 2.0.18
**OS**: Mac OS X 10.11.6
**Thrown From**: [atom-hydra](https://github.com/ojack/atom-hydra) package 0.2.10

### Stack Trace

Uncaught Error: (regl) webgl not supported, try upgrading your browser or graphics drivers http://get.webgl.org

```
At /Users/diego/.atom/packages/atom-hydra/node_modules/regl/dist/regl.js:49

Error: (regl) webgl not supported, try upgrading your browser or graphics drivers http://get.webgl.org
    at Function.raise (/packages/atom-hydra/node_modules/regl/dist/regl.js:47:15)
    at onDone (/packages/atom-hydra/node_modules/regl/dist/regl.js:888:15)
    at parseArgs (/packages/atom-hydra/node_modules/regl/dist/regl.js:966:5)
    at wrapREGL (/packages/atom-hydra/node_modules/regl/dist/regl.js:9101:16)
    at HydraSynth._initRegl (/packages/atom-hydra/node_modules/hydra-synth/index.js:123:32)
    at /packages/atom-hydra/node_modules/hydra-synth/index.js:42:10)
    at Main.start (/packages/atom-hydra/lib/main.js:171:18)
    at Object.toggle (/packages/atom-hydra/lib/atom-hydra.js:43:24)
    at HTMLElement.atomHydraToggle (/packages/atom-hydra/lib/atom-hydra.js:18:39)
    at CommandRegistry.handleCommandEvent (/Users/diego/Downloads/Atom.app/Contents/Resources/app/static/<embedded>:11:349922)
    at CommandRegistry.dispatch (/Users/diego/Downloads/Atom.app/Contents/Resources/app/static/<embedded>:11:348397)
    at AtomEnvironment.dispatchApplicationMenuCommand (/Users/diego/Downloads/Atom.app/Contents/Resources/app/static/<embedded>:1:716177)
    at EventEmitter.t (/Users/diego/Downloads/Atom.app/Contents/Resources/app/static/<embedded>:1:724100)
    at emitThree (events.js:136:13)
    at EventEmitter.emit (events.js:217:7)
```

### Commands

```
     -0:10.6.0 atom-hydra:toggle (atom-pane.pane.active)
```

### Non-Core Packages

```
atom-hydra 0.2.10 
tidalcycles 3.0.0 
```

**Comment by ojack** [comment]
This is an error with your graphics card, try running using the switch specified in the README
```Error: webgl not supported
Try running atom from the command line as follows: atom --ignore-gpu-blacklist```

**Comment by ndr-brt** [comment]
Same issue here, also with `--ignore-gpu-blacklist` flag.
atom version: 1.40.1
atom-hydra version: 0.2.12
